import { sql } from "drizzle-orm";
import {
	type AnySQLiteColumn,
	foreignKey,
	index,
	integer,
	primaryKey,
	real,
	sqliteTable,
	text,
	uniqueIndex,
} from "drizzle-orm/sqlite-core";

export const user = sqliteTable("user", {
	id: text("id").primaryKey(),
	name: text("name").notNull(),
	email: text("email").notNull().unique(),
	emailVerified: integer("email_verified", { mode: "boolean" })
		.notNull()
		.default(false),
	image: text("image"),
	accessStatus: text("access_status").notNull().default("waitlisted"),
	// Better Auth admin plugin: app-wide role ("admin" grants the admin API;
	// null/"user" is a regular member) and the ban controls it manages.
	role: text("role"),
	banned: integer("banned", { mode: "boolean" }).default(false),
	banReason: text("ban_reason"),
	banExpires: integer("ban_expires", { mode: "timestamp" }),
	createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
	updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
});

export const session = sqliteTable("session", {
	id: text("id").primaryKey(),
	expiresAt: integer("expires_at", { mode: "timestamp" }).notNull(),
	token: text("token").notNull().unique(),
	createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
	updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
	ipAddress: text("ip_address"),
	userAgent: text("user_agent"),
	userId: text("user_id")
		.notNull()
		.references(() => user.id, { onDelete: "cascade" }),
	// Better Auth organization plugin: the workspace the session is scoped to.
	activeOrganizationId: text("active_organization_id"),
	// Better Auth admin plugin: set on sessions created while impersonating.
	impersonatedBy: text("impersonated_by"),
});

export const account = sqliteTable("account", {
	id: text("id").primaryKey(),
	accountId: text("account_id").notNull(),
	providerId: text("provider_id").notNull(),
	userId: text("user_id")
		.notNull()
		.references(() => user.id, { onDelete: "cascade" }),
	accessToken: text("access_token"),
	refreshToken: text("refresh_token"),
	idToken: text("id_token"),
	accessTokenExpiresAt: integer("access_token_expires_at", {
		mode: "timestamp",
	}),
	refreshTokenExpiresAt: integer("refresh_token_expires_at", {
		mode: "timestamp",
	}),
	scope: text("scope"),
	password: text("password"),
	createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
	updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
});

export const verification = sqliteTable("verification", {
	id: text("id").primaryKey(),
	identifier: text("identifier").notNull(),
	value: text("value").notNull(),
	expiresAt: integer("expires_at", { mode: "timestamp" }).notNull(),
	createdAt: integer("created_at", { mode: "timestamp" }),
	updatedAt: integer("updated_at", { mode: "timestamp" }),
});

// Better Auth JWT plugin signing keys. Private keys are encrypted by Better
// Auth before storage; the public half is exposed through /api/auth/jwks.
export const jwks = sqliteTable("jwks", {
	id: text("id").primaryKey(),
	publicKey: text("public_key").notNull(),
	privateKey: text("private_key").notNull(),
	createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
	expiresAt: integer("expires_at", { mode: "timestamp_ms" }),
});

// Better Auth OAuth Provider tables. Keep these aligned with the schema
// generated by the installed @better-auth/oauth-provider version.
export const oauthClient = sqliteTable(
	"oauth_client",
	{
		id: text("id").primaryKey(),
		clientId: text("client_id").notNull().unique(),
		clientSecret: text("client_secret"),
		disabled: integer("disabled", { mode: "boolean" }).default(false),
		skipConsent: integer("skip_consent", { mode: "boolean" }),
		enableEndSession: integer("enable_end_session", { mode: "boolean" }),
		subjectType: text("subject_type"),
		scopes: text("scopes"),
		userId: text("user_id").references(() => user.id, {
			onDelete: "cascade",
		}),
		createdAt: integer("created_at", { mode: "timestamp_ms" }),
		updatedAt: integer("updated_at", { mode: "timestamp_ms" }),
		name: text("name"),
		uri: text("uri"),
		icon: text("icon"),
		contacts: text("contacts"),
		tos: text("tos"),
		policy: text("policy"),
		softwareId: text("software_id"),
		softwareVersion: text("software_version"),
		softwareStatement: text("software_statement"),
		redirectUris: text("redirect_uris").notNull(),
		postLogoutRedirectUris: text("post_logout_redirect_uris"),
		tokenEndpointAuthMethod: text("token_endpoint_auth_method"),
		grantTypes: text("grant_types"),
		responseTypes: text("response_types"),
		public: integer("public", { mode: "boolean" }),
		type: text("type"),
		requirePKCE: integer("require_pkce", { mode: "boolean" }),
		referenceId: text("reference_id"),
		// Better Auth stores this as a serialized JSON object and parses it at
		// the OAuth boundary. Keeping the Drizzle field as text avoids encoding
		// that JSON string a second time.
		metadata: text("metadata"),
	},
	(table) => ({
		userIdx: index("oauthClient_userId_idx").on(table.userId),
	}),
);

export const oauthRefreshToken = sqliteTable(
	"oauth_refresh_token",
	{
		id: text("id").primaryKey(),
		token: text("token").notNull().unique(),
		clientId: text("client_id")
			.notNull()
			.references(() => oauthClient.clientId, { onDelete: "cascade" }),
		sessionId: text("session_id").references(() => session.id, {
			onDelete: "set null",
		}),
		userId: text("user_id")
			.notNull()
			.references(() => user.id, { onDelete: "cascade" }),
		referenceId: text("reference_id"),
		expiresAt: integer("expires_at", { mode: "timestamp_ms" }),
		createdAt: integer("created_at", { mode: "timestamp_ms" }),
		revoked: integer("revoked", { mode: "timestamp_ms" }),
		authTime: integer("auth_time", { mode: "timestamp_ms" }),
		scopes: text("scopes").notNull(),
	},
	(table) => ({
		clientIdx: index("oauthRefreshToken_clientId_idx").on(table.clientId),
		sessionIdx: index("oauthRefreshToken_sessionId_idx").on(table.sessionId),
		userIdx: index("oauthRefreshToken_userId_idx").on(table.userId),
	}),
);

export const oauthAccessToken = sqliteTable(
	"oauth_access_token",
	{
		id: text("id").primaryKey(),
		token: text("token").unique(),
		clientId: text("client_id")
			.notNull()
			.references(() => oauthClient.clientId, { onDelete: "cascade" }),
		sessionId: text("session_id").references(() => session.id, {
			onDelete: "set null",
		}),
		userId: text("user_id").references(() => user.id, {
			onDelete: "cascade",
		}),
		referenceId: text("reference_id"),
		refreshId: text("refresh_id").references(() => oauthRefreshToken.id, {
			onDelete: "cascade",
		}),
		expiresAt: integer("expires_at", { mode: "timestamp_ms" }),
		createdAt: integer("created_at", { mode: "timestamp_ms" }),
		scopes: text("scopes").notNull(),
	},
	(table) => ({
		clientIdx: index("oauthAccessToken_clientId_idx").on(table.clientId),
		sessionIdx: index("oauthAccessToken_sessionId_idx").on(table.sessionId),
		userIdx: index("oauthAccessToken_userId_idx").on(table.userId),
		refreshIdx: index("oauthAccessToken_refreshId_idx").on(table.refreshId),
	}),
);

export const oauthConsent = sqliteTable(
	"oauth_consent",
	{
		id: text("id").primaryKey(),
		clientId: text("client_id")
			.notNull()
			.references(() => oauthClient.clientId, { onDelete: "cascade" }),
		userId: text("user_id").references(() => user.id, {
			onDelete: "cascade",
		}),
		referenceId: text("reference_id"),
		scopes: text("scopes").notNull(),
		createdAt: integer("created_at", { mode: "timestamp_ms" }),
		updatedAt: integer("updated_at", { mode: "timestamp_ms" }),
	},
	(table) => ({
		clientIdx: index("oauthConsent_clientId_idx").on(table.clientId),
		userIdx: index("oauthConsent_userId_idx").on(table.userId),
	}),
);

// Better Auth organization plugin tables. A "workspace" in the product is an
// organization here; members carry the role that drives page/task/canvas
// authorization.
export const organization = sqliteTable("organization", {
	id: text("id").primaryKey(),
	name: text("name").notNull(),
	slug: text("slug").notNull().unique(),
	logo: text("logo"),
	metadata: text("metadata"),
	createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
});

export const member = sqliteTable(
	"member",
	{
		id: text("id").primaryKey(),
		organizationId: text("organization_id")
			.notNull()
			.references(() => organization.id, { onDelete: "cascade" }),
		userId: text("user_id")
			.notNull()
			.references(() => user.id, { onDelete: "cascade" }),
		role: text("role").notNull().default("member"),
		createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
	},
	(table) => ({
		orgUserIdx: uniqueIndex("member_org_user_idx").on(
			table.organizationId,
			table.userId,
		),
	}),
);

export const invitation = sqliteTable("invitation", {
	id: text("id").primaryKey(),
	organizationId: text("organization_id")
		.notNull()
		.references(() => organization.id, { onDelete: "cascade" }),
	email: text("email").notNull(),
	role: text("role"),
	status: text("status").notNull().default("pending"),
	expiresAt: integer("expires_at", { mode: "timestamp" }).notNull(),
	createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
	inviterId: text("inviter_id")
		.notNull()
		.references(() => user.id, { onDelete: "cascade" }),
});

// App-owned authorization layered on top of OAuth. Better Auth proves the
// user/client identity; this row decides what that pair may do in Haunter.
export const mcpConnection = sqliteTable(
	"mcp_connection",
	{
		id: text("id").primaryKey(),
		userId: text("user_id")
			.notNull()
			.references(() => user.id, { onDelete: "cascade" }),
		clientId: text("client_id")
			.notNull()
			.references(() => oauthClient.clientId, { onDelete: "cascade" }),
		permissionProfile: text("permission_profile", {
			enum: ["view", "edit", "full"],
		}).notNull(),
		status: text("status", {
			enum: ["active", "revoked"],
		})
			.notNull()
			.default("active"),
		lastUsedAt: integer("last_used_at", { mode: "timestamp" }),
		createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
		updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
	},
	(table) => ({
		userClientIdx: uniqueIndex("mcp_connection_user_client_idx").on(
			table.userId,
			table.clientId,
		),
		userStatusIdx: index("mcp_connection_user_status_idx").on(
			table.userId,
			table.status,
		),
	}),
);

export const mcpConnectionWorkspace = sqliteTable(
	"mcp_connection_workspace",
	{
		connectionId: text("connection_id")
			.notNull()
			.references(() => mcpConnection.id, { onDelete: "cascade" }),
		workspaceId: text("workspace_id")
			.notNull()
			.references(() => organization.id, { onDelete: "cascade" }),
		createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
	},
	(table) => ({
		pk: primaryKey({
			name: "mcp_connection_workspace_pk",
			columns: [table.connectionId, table.workspaceId],
		}),
		workspaceIdx: index("mcp_connection_workspace_workspace_idx").on(
			table.workspaceId,
		),
	}),
);

// Metadata-only hosted MCP activity. Arguments, results, tokens, and page/task
// content are intentionally never stored here.
export const mcpConnectionActivity = sqliteTable(
	"mcp_connection_activity",
	{
		id: text("id").primaryKey(),
		connectionId: text("connection_id")
			.notNull()
			.references(() => mcpConnection.id, { onDelete: "cascade" }),
		userId: text("user_id")
			.notNull()
			.references(() => user.id, { onDelete: "cascade" }),
		workspaceId: text("workspace_id").references(() => organization.id, {
			onDelete: "set null",
		}),
		capability: text("capability").notNull(),
		status: text("status", { enum: ["success", "error"] }).notNull(),
		resourceType: text("resource_type", { enum: ["page", "task"] }),
		resourceId: text("resource_id"),
		resourceLabel: text("resource_label"),
		durationMs: integer("duration_ms").notNull(),
		errorCode: text("error_code"),
		createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
	},
	(table) => ({
		userCreatedIdx: index("mcp_activity_user_created_idx").on(
			table.userId,
			table.createdAt,
		),
		connectionCreatedIdx: index("mcp_activity_connection_created_idx").on(
			table.connectionId,
			table.createdAt,
		),
	}),
);

// @better-auth/agent-auth plugin: an agent runtime (e.g. an MCP client or
// automation host) that agents register under.
export const agentHost = sqliteTable("agent_host", {
	id: text("id").primaryKey(),
	name: text("name"),
	userId: text("user_id").references(() => user.id, { onDelete: "cascade" }),
	defaultCapabilities: text("default_capabilities"),
	publicKey: text("public_key"),
	kid: text("kid"),
	jwksUrl: text("jwks_url"),
	enrollmentTokenHash: text("enrollment_token_hash"),
	enrollmentTokenExpiresAt: integer("enrollment_token_expires_at", {
		mode: "timestamp",
	}),
	status: text("status").notNull(),
	activatedAt: integer("activated_at", { mode: "timestamp" }),
	expiresAt: integer("expires_at", { mode: "timestamp" }),
	lastUsedAt: integer("last_used_at", { mode: "timestamp" }),
	createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
	updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
});

// An AI agent identity. Delegated agents act for userId with capability
// grants scoped well below that user's own rights.
export const agent = sqliteTable("agent", {
	id: text("id").primaryKey(),
	name: text("name").notNull(),
	userId: text("user_id").references(() => user.id, { onDelete: "cascade" }),
	hostId: text("host_id")
		.notNull()
		.references(() => agentHost.id, { onDelete: "cascade" }),
	status: text("status").notNull(),
	mode: text("mode").notNull(),
	publicKey: text("public_key").notNull(),
	kid: text("kid"),
	jwksUrl: text("jwks_url"),
	lastUsedAt: integer("last_used_at", { mode: "timestamp" }),
	activatedAt: integer("activated_at", { mode: "timestamp" }),
	expiresAt: integer("expires_at", { mode: "timestamp" }),
	metadata: text("metadata"),
	createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
	updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
});

export const agentCapabilityGrant = sqliteTable("agent_capability_grant", {
	id: text("id").primaryKey(),
	agentId: text("agent_id")
		.notNull()
		.references(() => agent.id, { onDelete: "cascade" }),
	capability: text("capability").notNull(),
	deniedBy: text("denied_by").references(() => user.id, {
		onDelete: "cascade",
	}),
	grantedBy: text("granted_by").references(() => user.id, {
		onDelete: "cascade",
	}),
	expiresAt: integer("expires_at", { mode: "timestamp" }),
	createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
	updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
	status: text("status").notNull(),
	reason: text("reason"),
	constraints: text("constraints"),
});

// App-owned execution history for Agent Auth capabilities. This intentionally
// stores only derived resource metadata, never raw arguments or page content.
export const agentActivity = sqliteTable(
	"agent_activity",
	{
		id: text("id").primaryKey(),
		agentId: text("agent_id")
			.notNull()
			.references(() => agent.id, { onDelete: "cascade" }),
		userId: text("user_id")
			.notNull()
			.references(() => user.id, { onDelete: "cascade" }),
		workspaceId: text("workspace_id").references(() => organization.id, {
			onDelete: "set null",
		}),
		capability: text("capability").notNull(),
		status: text("status", { enum: ["success", "error"] }).notNull(),
		resourceType: text("resource_type", { enum: ["page", "task"] }),
		resourceId: text("resource_id"),
		resourceLabel: text("resource_label"),
		durationMs: integer("duration_ms").notNull(),
		error: text("error"),
		createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
	},
	(table) => ({
		userCreatedIdx: index("agent_activity_user_created_idx").on(
			table.userId,
			table.createdAt,
		),
		agentCreatedIdx: index("agent_activity_agent_created_idx").on(
			table.agentId,
			table.createdAt,
		),
	}),
);

export const approvalRequest = sqliteTable("approval_request", {
	id: text("id").primaryKey(),
	method: text("method").notNull(),
	agentId: text("agent_id").references(() => agent.id, {
		onDelete: "cascade",
	}),
	hostId: text("host_id").references(() => agentHost.id, {
		onDelete: "cascade",
	}),
	userId: text("user_id").references(() => user.id, { onDelete: "cascade" }),
	capabilities: text("capabilities"),
	status: text("status").notNull(),
	userCodeHash: text("user_code_hash"),
	loginHint: text("login_hint"),
	bindingMessage: text("binding_message"),
	clientNotificationToken: text("client_notification_token"),
	clientNotificationEndpoint: text("client_notification_endpoint"),
	deliveryMode: text("delivery_mode"),
	interval: integer("interval").notNull(),
	lastPolledAt: integer("last_polled_at", { mode: "timestamp" }),
	expiresAt: integer("expires_at", { mode: "timestamp" }).notNull(),
	createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
	updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
});

export const pages = sqliteTable(
	"pages",
	{
		id: text("id").primaryKey(),
		userId: text("user_id")
			.notNull()
			.references(() => user.id, { onDelete: "cascade" }),
		workspaceId: text("workspace_id")
			.notNull()
			.references(() => organization.id, { onDelete: "cascade" }),
		parentPageId: text("parent_page_id").references(
			(): AnySQLiteColumn => pages.id,
			{ onDelete: "cascade" },
		),
		title: text("title").notNull(),
		icon: text("icon"),
		position: real("position").notNull(),
		content: text("content").notNull().default("[]"),
		searchText: text("search_text").notNull().default(""),
		contentUpdatedAt: text("content_updated_at").notNull(),
		deletedAt: text("deleted_at"),
		createdAt: text("created_at").notNull(),
		updatedAt: text("updated_at").notNull(),
	},
	(table) => ({
		workspaceIdx: index("pages_workspace_idx").on(table.workspaceId),
		workspaceDeletedPositionIdx: index(
			"pages_workspace_deleted_position_idx",
		).on(table.workspaceId, table.deletedAt, table.position),
		workspaceDeletedUpdatedIdx: index("pages_workspace_deleted_updated_idx").on(
			table.workspaceId,
			table.deletedAt,
			table.updatedAt,
		),
		parentIdx: index("pages_parent_idx").on(table.parentPageId),
	}),
);

export const pageUserState = sqliteTable(
	"page_user_state",
	{
		userId: text("user_id")
			.notNull()
			.references(() => user.id, { onDelete: "cascade" }),
		workspaceId: text("workspace_id")
			.notNull()
			.references(() => organization.id, { onDelete: "cascade" }),
		pageId: text("page_id")
			.notNull()
			.references(() => pages.id, { onDelete: "cascade" }),
		favoritedAt: text("favorited_at"),
		lastViewedAt: text("last_viewed_at"),
	},
	(table) => ({
		pk: primaryKey({ columns: [table.userId, table.pageId] }),
		membershipFk: foreignKey({
			columns: [table.workspaceId, table.userId],
			foreignColumns: [member.organizationId, member.userId],
			name: "page_user_state_membership_fk",
		}).onDelete("cascade"),
		favoritesIdx: index("page_user_state_favorites_idx").on(
			table.workspaceId,
			table.userId,
			table.favoritedAt,
		),
		recentsIdx: index("page_user_state_recents_idx").on(
			table.workspaceId,
			table.userId,
			table.lastViewedAt,
		),
	}),
);

export const tasks = sqliteTable(
	"tasks",
	{
		id: text("id").primaryKey(),
		userId: text("user_id")
			.notNull()
			.references(() => user.id, { onDelete: "cascade" }),
		workspaceId: text("workspace_id")
			.notNull()
			.references(() => organization.id, { onDelete: "cascade" }),
		// The member a task is assigned to (null = unassigned). Drives "My Tasks"
		// once a workspace has more than one person.
		assigneeId: text("assignee_id").references(() => user.id, {
			onDelete: "set null",
		}),
		pageId: text("page_id").references(() => pages.id, {
			onDelete: "cascade",
		}),
		sourceBlockId: text("source_block_id"),
		title: text("title").notNull(),
		completed: integer("completed", { mode: "boolean" })
			.notNull()
			.default(false),
		dueDate: text("due_date"),
		dueTime: text("due_time"),
		reminderOffsetMinutes: integer("reminder_offset_minutes"),
		reminderConfiguredAt: text("reminder_configured_at"),
		completedAt: text("completed_at"),
		createdAt: text("created_at").notNull(),
		updatedAt: text("updated_at").notNull(),
	},
	(table) => ({
		pageBlockIdx: uniqueIndex("tasks_page_block_idx")
			.on(table.pageId, table.sourceBlockId)
			.where(sql`source_block_id IS NOT NULL`),
		workspaceIdx: index("tasks_workspace_idx").on(
			table.workspaceId,
			table.completed,
		),
		workspaceListIdx: index("tasks_workspace_list_idx").on(
			table.workspaceId,
			table.completed,
			table.dueDate,
			table.dueTime,
			table.createdAt,
		),
		assigneeIdx: index("tasks_assignee_idx").on(
			table.workspaceId,
			table.assigneeId,
			table.completed,
		),
		assigneeListIdx: index("tasks_assignee_list_idx").on(
			table.workspaceId,
			table.assigneeId,
			table.completed,
			table.dueDate,
			table.dueTime,
			table.createdAt,
		),
		overdueNotificationIdx: index("tasks_overdue_notification_idx").on(
			table.completed,
			table.dueDate,
			table.dueTime,
			table.assigneeId,
		),
		reminderCandidateIdx: index("tasks_reminder_candidate_idx").on(
			table.completed,
			table.reminderOffsetMinutes,
			table.dueDate,
			table.assigneeId,
		),
		pageIdx: index("tasks_page_idx").on(table.pageId),
		userIdx: index("tasks_user_idx").on(table.userId),
	}),
);

export const notificationPreferences = sqliteTable("notification_preferences", {
	userId: text("user_id")
		.primaryKey()
		.references(() => user.id, { onDelete: "cascade" }),
	overdueTasksEnabled: integer("overdue_tasks_enabled", { mode: "boolean" })
		.notNull()
		.default(true),
	taskAssignmentsEnabled: integer("task_assignments_enabled", {
		mode: "boolean",
	})
		.notNull()
		.default(true),
	taskRemindersEnabled: integer("task_reminders_enabled", {
		mode: "boolean",
	})
		.notNull()
		.default(true),
	timezone: text("timezone").notNull().default("UTC"),
	timezoneConfigured: integer("timezone_configured", { mode: "boolean" })
		.notNull()
		.default(false),
	createdAt: text("created_at").notNull(),
	updatedAt: text("updated_at").notNull(),
});

export const changelogUserState = sqliteTable("changelog_user_state", {
	userId: text("user_id")
		.primaryKey()
		.references(() => user.id, { onDelete: "cascade" }),
	lastSeenVersion: text("last_seen_version").notNull(),
	createdAt: text("created_at").notNull(),
	updatedAt: text("updated_at").notNull(),
});

export const pushSubscriptions = sqliteTable(
	"push_subscriptions",
	{
		id: text("id").primaryKey(),
		userId: text("user_id")
			.notNull()
			.references(() => user.id, { onDelete: "cascade" }),
		endpoint: text("endpoint").notNull(),
		expirationTime: integer("expiration_time"),
		p256dh: text("p256dh").notNull(),
		auth: text("auth").notNull(),
		createdAt: text("created_at").notNull(),
		updatedAt: text("updated_at").notNull(),
	},
	(table) => ({
		endpointIdx: uniqueIndex("push_subscriptions_endpoint_idx").on(
			table.endpoint,
		),
		userIdx: index("push_subscriptions_user_idx").on(table.userId),
	}),
);

export const notifications = sqliteTable(
	"notifications",
	{
		id: text("id").primaryKey(),
		userId: text("user_id")
			.notNull()
			.references(() => user.id, { onDelete: "cascade" }),
		workspaceId: text("workspace_id")
			.notNull()
			.references(() => organization.id, { onDelete: "cascade" }),
		kind: text("kind").notNull(),
		entityId: text("entity_id").notNull(),
		entityVersion: text("entity_version").notNull(),
		payload: text("payload").notNull(),
		readAt: text("read_at"),
		createdAt: text("created_at").notNull(),
		actionState: text("action_state"),
		actionAt: text("action_at"),
		snoozedUntil: text("snoozed_until"),
		pushState: text("push_state").notNull().default("pending"),
		pushAttempts: integer("push_attempts").notNull().default(0),
		pushNextAttemptAt: text("push_next_attempt_at"),
		pushLeaseUntil: text("push_lease_until"),
		pushDeliveredAt: text("push_delivered_at"),
	},
	(table) => ({
		dedupeIdx: uniqueIndex("notifications_dedupe_idx").on(
			table.userId,
			table.kind,
			table.entityId,
			table.entityVersion,
		),
		userCreatedIdx: index("notifications_user_created_idx").on(
			table.userId,
			table.createdAt,
			table.id,
		),
		userUnreadIdx: index("notifications_user_unread_idx").on(
			table.userId,
			table.readAt,
			table.createdAt,
		),
		pushPendingIdx: index("notifications_push_pending_idx").on(
			table.pushState,
			table.pushNextAttemptAt,
			table.pushLeaseUntil,
		),
		snoozedIdx: index("notifications_snoozed_idx").on(
			table.actionState,
			table.snoozedUntil,
		),
	}),
);

export const canvases = sqliteTable(
	"canvases",
	{
		id: text("id").primaryKey(),
		userId: text("user_id")
			.notNull()
			.references(() => user.id, { onDelete: "cascade" }),
		workspaceId: text("workspace_id")
			.notNull()
			.references(() => organization.id, { onDelete: "cascade" }),
		pageId: text("page_id")
			.notNull()
			.references(() => pages.id, { onDelete: "cascade" }),
		snapshot: text("snapshot").notNull().default("{}"),
		createdAt: text("created_at").notNull(),
		updatedAt: text("updated_at").notNull(),
	},
	(table) => ({
		pageIdx: index("canvases_page_idx").on(table.pageId),
	}),
);

// Page-to-page references (pageLink blocks and inline mentions), reconciled
// from the document on every content save. Backlinks are read from target.
export const pageLinks = sqliteTable(
	"page_links",
	{
		sourcePageId: text("source_page_id")
			.notNull()
			.references((): AnySQLiteColumn => pages.id, { onDelete: "cascade" }),
		targetPageId: text("target_page_id")
			.notNull()
			.references((): AnySQLiteColumn => pages.id, { onDelete: "cascade" }),
		userId: text("user_id")
			.notNull()
			.references(() => user.id, { onDelete: "cascade" }),
		createdAt: text("created_at").notNull(),
	},
	(table) => ({
		pk: primaryKey({ columns: [table.sourcePageId, table.targetPageId] }),
		targetIdx: index("page_links_target_idx").on(table.targetPageId),
	}),
);

// Public read-only share links. One active link per page; the row's token is
// the capability — deleting the row revokes the link.
export const pageShares = sqliteTable(
	"page_shares",
	{
		id: text("id").primaryKey(),
		pageId: text("page_id")
			.notNull()
			.references(() => pages.id, { onDelete: "cascade" }),
		workspaceId: text("workspace_id")
			.notNull()
			.references(() => organization.id, { onDelete: "cascade" }),
		token: text("token").notNull().unique(),
		createdBy: text("created_by")
			.notNull()
			.references(() => user.id, { onDelete: "cascade" }),
		createdAt: text("created_at").notNull(),
	},
	(table) => ({
		pageIdx: uniqueIndex("page_shares_page_idx").on(table.pageId),
	}),
);

// Point-in-time snapshots of page documents. Written as checkpoints from the
// content-save path (at most one per interval) and always before a restore,
// so going back never loses the state you left.
export const pageVersions = sqliteTable(
	"page_versions",
	{
		id: text("id").primaryKey(),
		pageId: text("page_id")
			.notNull()
			.references(() => pages.id, { onDelete: "cascade" }),
		workspaceId: text("workspace_id")
			.notNull()
			.references(() => organization.id, { onDelete: "cascade" }),
		title: text("title").notNull(),
		icon: text("icon"),
		content: text("content").notNull(),
		// What produced the snapshot: a periodic "checkpoint" or a "restore".
		cause: text("cause").notNull().default("checkpoint"),
		createdBy: text("created_by")
			.notNull()
			.references(() => user.id, { onDelete: "cascade" }),
		createdAt: text("created_at").notNull(),
	},
	(table) => ({
		pageCreatedIdx: index("page_versions_page_created_idx").on(
			table.pageId,
			table.createdAt,
		),
	}),
);
